server:
  port: 8080
spring:
  codec:
    max-in-memory-size: 3MB
  application:
    name: "CrediYa_Sol"
  devtools:
    add-properties: false


  # R2DBC (WebFlux)
  r2dbc:
    host: ${ADAPTERS_R2DBC_HOST}
    port: ${ADAPTERS_R2DBC_PORT:5432}
    database: ${ADAPTERS_R2DBC_DATABASE:postgres}
    schema: ${ADAPTERS_R2DBC_SCHEMA}
    username: ${ADAPTERS_R2DBC_USERNAME}
    password: ${ADAPTERS_R2DBC_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"

routes:
  paths:
    solicitudes: "/api/v1/solicitudes"
    solicitudesById: "/api/v1/solicitudes/{id}"
    solicitudesRevision: "/api/v1/solicitudes/revision"

adapters:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

logging:
  level:
    root: INFO
    co.com.autenticacion: TRACE
    org.springframework.r2dbc: DEBUG

usuarios:
  base-url: ${USUARIOS_BASE_URL:http://localhost:8081}